"""empty message

Revision ID: 03f8e0319c46
Revises: aa4934553405
Create Date: 2020-05-31 11:24:30.758511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03f8e0319c46'
down_revision = 'aa4934553405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_labels', sa.Column('label', sa.String(length=255), nullable=False))
    op.drop_column('card_labels', 'labels')
    op.add_column('cards', sa.Column('labels', sa.String(length=255), nullable=True))
    op.drop_column('cards', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('label', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('cards', 'labels')
    op.add_column('card_labels', sa.Column('labels', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('card_labels', 'label')
    # ### end Alembic commands ###
