"""empty message

Revision ID: 4d8fb421884c
Revises: 6685a4dc0cf8
Create Date: 2020-05-25 17:06:56.348370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d8fb421884c'
down_revision = '6685a4dc0cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('text', sa.String(length=255), nullable=False))
    op.drop_column('cards', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('cards', 'text')
    # ### end Alembic commands ###
