"""empty message

Revision ID: 60ab351b0cf6
Revises: 
Create Date: 2020-05-23 22:41:28.180122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60ab351b0cf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_members', sa.Column('memberId', sa.String(length=255), nullable=False))
    op.drop_column('card_members', 'member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_members', sa.Column('member', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('card_members', 'memberId')
    # ### end Alembic commands ###
