"""empty message

Revision ID: 6685a4dc0cf8
Revises: 60ab351b0cf6
Create Date: 2020-05-25 17:03:30.957063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6685a4dc0cf8'
down_revision = '60ab351b0cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('cards', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'cards')
    # ### end Alembic commands ###
