"""empty message

Revision ID: 890a81a4ab70
Revises: 963975495215
Create Date: 2020-06-01 21:42:39.773589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890a81a4ab70'
down_revision = '963975495215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cover', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cover')
    # ### end Alembic commands ###
