"""empty message

Revision ID: 963975495215
Revises: 03f8e0319c46
Create Date: 2020-05-31 13:23:28.271612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963975495215'
down_revision = '03f8e0319c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boards_ibfk_1', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['ownerId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('card_labels_ibfk_1', 'card_labels', type_='foreignkey')
    op.create_foreign_key(None, 'card_labels', 'cards', ['cardId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('card_members_ibfk_1', 'card_members', type_='foreignkey')
    op.create_foreign_key(None, 'card_members', 'cards', ['cardId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cards_ibfk_1', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'lists', ['listId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lists_ibfk_1', 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['boardId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key('lists_ibfk_1', 'lists', 'boards', ['boardId'], ['id'])
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_ibfk_1', 'cards', 'lists', ['listId'], ['id'])
    op.drop_constraint(None, 'card_members', type_='foreignkey')
    op.create_foreign_key('card_members_ibfk_1', 'card_members', 'cards', ['cardId'], ['id'])
    op.drop_constraint(None, 'card_labels', type_='foreignkey')
    op.create_foreign_key('card_labels_ibfk_1', 'card_labels', 'cards', ['cardId'], ['id'])
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_ibfk_1', 'boards', 'users', ['ownerId'], ['id'])
    # ### end Alembic commands ###
