"""empty message

Revision ID: aa4934553405
Revises: 18aa6c0f7b29
Create Date: 2020-05-31 11:04:42.027723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4934553405'
down_revision = '18aa6c0f7b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('label', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'label')
    # ### end Alembic commands ###
